x-application: &application
  image: jersey-petitions/ruby
  build: docker/ruby
  volumes:
    - .:/app
    - bundle:/bundle
    - cache:/cache
    - node_modules:/app/node_modules
  tmpfs:
    - /tmp/pids/
  depends_on:
    - postgres
    - mailcatcher

x-environment: &environment
  DATABASE_URL: "postgres://postgres:2nPKkrEePQ5n7yQy@postgres:5432"
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
  SMTP_HOST: "mailcatcher"
  SMTP_PORT: "1025"
  SPROCKETS_CACHE: "/cache"
  PIDFILE: "/tmp/pids/server.pid"

services:
  postgres:
    image: postgres:14
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2nPKkrEePQ5n7yQy
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  mailcatcher:
    image: jersey-petitions/mailcatcher
    build: docker/mailcatcher
    expose:
      - "1025"
    ports:
      - "127.0.0.1:1080:1080"

  web:
    <<: *application
    environment:
      <<: *environment
    command: [
      "rails", "server",
      "-b", "0.0.0.0",
      "-p", "3000"
    ]
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true

  worker:
    <<: *application
    environment:
      <<: *environment
    command: [ "rake", "jobs:work" ]

volumes:
  bundle:
  db:
  cache:
  node_modules:
